Added JSS styling for CaregroupCard Component
evantaurusta/ifgf-seattle pull request #4
Opened 2018-07-07 23:31 UTC by evantaurusta

2018-07-08 05:40 UTC, sdkitono commented on src/App.css
> +  text-align: center;
why need text-align center in body?

2018-07-08 05:49 UTC, sdkitono commented on src/components/Card/CaregroupCard.js
> +      return null;
if you already using map do we still need to explicitly return null

2018-07-08 05:54 UTC, sdkitono commented on src/containers/Caregroup/Caregroup.js
> +          <CaregroupCard />
Hmm this is weird why you dont put the map of the states in here instead? The right approach is to make CareGroupCard a function component instead that receives props and just render it without business logic. You should put the business logic in this component instead

2018-07-08 05:55 UTC, sdkitono requested changes
Please see comments above for the changes. You can ask me for further details.

2018-07-10 22:26 UTC, evantaurusta commented on src/containers/Caregroup/Caregroup.js
> +          <CaregroupCard />
like this? https://www.youtube.com/watch?v=Lx0AE-mhNlg

2018-07-21 23:25 UTC, sdkitono commented on src/components/Card/CaregroupCard.js
> +
Remove spacing

2018-07-21 23:26 UTC, sdkitono approved these changes

2018-07-21 23:26 UTC, merged